language: python
python:
- '3.2'
- '3.3'
- '3.4'
- '3.5'
cache:
  pip: false
deploy:
  provider: pypi
  user: iyzico
  password:
    secure: hNtFDVw0otRJOJFs1a4FyGl+B66N62NolX/UaafriPZUyhjOLT8+LeIQUIAM94+y0gqO5IJr9ejFyvBpfuISx8wfsODsLedsqXxMTfHXE9v2elW5gunH3Mv1VBldgM6usOduYoDfPPsk40bEKtmJM1rxaz9l9sw1LaHhZF1FzX2GJXzPZWcAmSD4jSqEPeK1YP+BFSd8O1x2CTVAwvhhnu32+rGtroLjpgxpediVLuNVccw8HRoRFI6Q0ahXBO6l2d8EJAwBv8rDwO3U+96f+5sljZvjfqErFLE3CSN7zuiBltZGEPXHWJlOHDhsRBr8VorGXR0ctTgi8+oO0gaygZIrophwOoCUgH6Zv9KYQVgW2sjVFncttumT697cqCCojFaSqAQE6wQ4ofKatol9oGABXsTCCGL+emQDGo9oPwuym31ZNVUGr2iVkVcXGMGR6/PjSGmkyo07XDqt+Mtb5zQxlFLkATUYiPHUWqaGEmuiMKkHDOy+Yw/Em0FRozoAgjb7n14ohmS5UBTjjc6m35nsWaI6dlxCJmF6kYCcBEb1oNXFtydi20v5ZBvz0zN4lr6S/Ve+bJOEOu6EF15LOgVRrdJuWWsG4IyhdVw4Fh6sRVce3uqkvvz1jZftPyuJgRwy0M+fEiuuCYSsNAk7mVA6D4aEfgVX2+SBiVDssfQ=
  on:
    tags: true
    branch: master
install:
- pip install unittest2
script:
- echo "TODO"
