language: python

python:
  - "pypy"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

cache:
  apt: true
  pip: false

script:
  - touch foo

deploy:
  provider: pypi
  user: iyzico
  password:
    secure: my_secure_password
  on:
    tags: true
    branch: master