language: python
python:
- '3.2'
- '3.3'
- '3.4'
- '3.5'
cache:
  pip: false
deploy:
  provider: pypi
  user: iyzico
  password:
    secure: eEZBtB4Sdd9UB7rhGlsyhO/isPncE9MDj9ATxv5Bq7miAQmLiBoKLeiCfFQoUyJOjSKRvj1rhLWwlxbW3JkhFTxM8uT0PyplQGLYN7CittHTl6vQf5/cNdcrtMCOwrB1ksEkWhV2xd4B7d6m6J5lugYiC69kdM/a0RImBQPTkT/1QkjSYmpsh4fGc0QZ66f2Btfz8uGXGpGwlI0NvxY3TFUe0f26rvZQcWgoUGFs0yGMKB8xB8+Tb2yInpZ3ZkVup+y0ZUrOrozL13jvjezT+Q23gN7VZewx5XSMwfy+g5/hfXlIc8e7Pz58Vu2viAy70BcUSRKHfgGiNaC9kW9ZOhJ4znL5C3rZaa4uZtJiPgMCQJRDFYt9f2/sTKQxl4dAaKZsVeWh4/0cI8JUWouNPEPQd0n8Ikz57xpdEliCyjj4jMHOAV6HUjX6kwX93X4+KXViBKf+BQ25ODbrwJ9Sm7JIEILPZH3lhSKii7CXHdNuK6FqUgYIUGmfjuz7gNe2ZzTVOUWTH3aikLxLC9qQfCP2Nzf3P/ypdOy9s/XFOmylxNlEz6uVLjFecYluOOeu1rGzw4bDgUBXny5+cjHeuH7segw6Lb8TYbZrfC8dLHjuXn5+sZ0N8L+5SzcxXvdLBQDrec7t7dd2bPxGRpEKAi/3De7IWJw7nPC3yDvqo0I=
  on:
    tags: true
    branch: master
  skip_cleanup: true
install:
  - pip install unittest2
script:
    - echo "TODO"